fm = 2000;
fc = 100000;
fs = 1001;
t = -1:1/fs:1;
A1 = 1;
m = cos(2*pi*fm*t);
c = cos(2*pi*fc*t);
Udsbfc1 = (2*A1 + A1*m).*c;
m1 = 2*A1 + A1*m;
m2 = -2*A1 - A1*m;
Udsbfc2 = (1.25*A1 + A1*m).*c;
m3 = 1.25*A1 + A1*m;
m4 = -1.25*A1 - A1*m;
Udsbfc3 = (A1 + A1*m).*c;
m5 = A1 + A1*m;
m6 = -A1 - A1*m;
Udsbfc4 = (2*A1/3 + A1*m).*c;
m7 = 2*A1/3 + A1*m;
m8 = -2*A1/3 - A1*m;
figure;
subplot(4,1,1);
plot(t,Udsbfc1,'g');
xlabel('time');
ylabel('UDSB-FC waveform');
title('MI = 0.5');
hold on;
plot(t,m1,'r');
hold on;
plot(t,m2,'b');
hold off;
subplot(4,1,2);
plot(t,Udsbfc2,'g');
hold on;
xlabel('time');
ylabel('UDSB-FC waveform');
title('MI = 0.8');
plot(t,m3,'r');
hold on;
plot(t,m4,'b');
hold off;
subplot(4,1,3);
plot(t,Udsbfc3,'g');
hold on;
xlabel('time');
ylabel('UDSB-FC waveform');
title('MI = 1');
plot(t,m5,'r');
hold on;
plot(t,m6,'b');
hold off;
subplot(4,1,4);
plot(t,Udsbfc4,'g');
hold on;
xlabel('time');
ylabel('UDSB-FC waveform ');
title('MI = 1.5');
plot(t,m7,'r');
hold on;
plot(t,m8,'b');
hold off;