fs= 100;
t = -1:1/fs:1;
fc = 100000;
Am =1;
Ac =2;
m = sawtooth(1000*t);
c = cos(2*pi*fc*t);
UDsbfc = (Ac + Am*m).*c;
UDsbsc = Ac*Am*m.*c;
x1 = fft(UDsbfc);
y1 = fftshift(x1);
x2 = fft(UDsbsc);
y2 = fftshift(x2);
figure;
subplot(2,1,1);
plot(t,real(y1));
xlabel('frequency');
ylabel('UDSB-FC spectrum');
subplot(2,1,2);
plot(t,real(y2));
xlabel('frequency');
ylabel('UDSB-SC spectrum');