fm = 1000;
fc = 10000;
fs = 1001;
t = -1:1/fs:1;
t1 = -1:1/fs:1-1/fs;
Am = 1;
Ac = 10;
kf = 50;
m = Am*cos(2*pi*fm*t);
c = Ac*cos(2*pi*fc*t);
phi = (kf/fm)*cumsum(m);
U = Ac*cos(2*pi*fc*t + phi);
Y1 = diff(U);
[yupper,ylower] = envelope(Y1);
dc = mean(yupper);
mu = 2*(dc -yupper);
Z1 = fft(m);
Z2 = fft(U);
Z3 = fft(yupper);
Z4 = fft(mu);
figure;
subplot(2,2,1);
plot(t,fftshift(real(Z1)),'g');grid on;
title('Spectrum of message');
subplot(2,2,2);
plot(t,fftshift(real(Z2)),'g');grid on;
title('Spectrum of Modulated FM');
subplot(2,2,3);
plot(t1,fftshift(real(Z3)),'g');grid on;
title('Spectrum of rectified message');
subplot(2,2,4);
plot(t1,fftshift(real(Z4)),'g');grid on;
title('Spectrum of recovered message');